In [1]:
import numpy as np

In [2]:
import pandas as pd


In [3]:
import random

In [ ]:
################################11111

In [5]:
data1=np.random.randint(3,10,5)
print(data1)

[6 5 7 7 4]


In [8]:
s1=pd.Series(data1,index=["a","b","c","d","e"])
print(s1)

a    6
b    5
c    7
d    7
e    4
dtype: int32


In [ ]:
#################################################2222

In [14]:
s1[-3:]

c    7
d    7
e    4
dtype: int32

In [16]:
s1["c":"e"]

c    7
d    7
e    4
dtype: int32

In [ ]:
#######################################3333333

In [29]:
data={"year":pd.Series(np.arange(2017,2020,1),index=list("012")),
      "price":pd.Series(np.arange(10,40,10),index=list("012"))}
pd.DataFrame(data)

year  price
0  2017     10
1  2018     20
2  2019     30

In [ ]:
#######################################444444444

In [18]:
data2=np.random.randint(5,15,(5,3))
print(data2)

[[ 8  6 14]
 [12 11 13]
 [13 14  5]
 [13  5 10]
 [ 6 11 14]]


In [30]:
df_test=pd.DataFrame(data2,index=list("abcde"),columns=["one","two","three"])
print(df_test)

   one  two  three
a    8    6     14
b   12   11     13
c   13   14      5
d   13    5     10
e    6   11     14


In [ ]:
################################555555

In [40]:
df_test.loc["a","one"]=" "
df_test.loc["c","two"]=-99
df_test.loc["c","three"]=-99
df_test.loc["a","two"]=-100
df_test["four"]="test"
print(df_test)


  one  two  three  four
a     -100     14  test
b  12   11     13  test
c  13  -99    -99  test
d  13    5     10  test
e   6   11     14  test


In [46]:
df_change=df_test.reindex(["a","b","c","d","e","f","g","h"])
print(df_change)

   one    two  three  four
a      -100.0   14.0  test
b   12   11.0   13.0  test
c   13  -99.0  -99.0  test
d   13    5.0   10.0  test
e    6   11.0   14.0  test
f  NaN    NaN    NaN   NaN
g  NaN    NaN    NaN   NaN
h  NaN    NaN    NaN   NaN


In [ ]:
#######################################666666

In [50]:
df1=df_change.dropna()
print(df1)

  one    two  three  four
a     -100.0   14.0  test
b  12   11.0   13.0  test
c  13  -99.0  -99.0  test
d  13    5.0   10.0  test
e   6   11.0   14.0  test


In [48]:
###################77777777


In [52]:
df2=df_change.dropna(how="all")
print(df2)

  one    two  three  four
a     -100.0   14.0  test
b  12   11.0   13.0  test
c  13  -99.0  -99.0  test
d  13    5.0   10.0  test
e   6   11.0   14.0  test


In [53]:
###############8888888


In [55]:
df3=df_change.fillna(0)
print(df3)

  one    two  three  four
a     -100.0   14.0  test
b  12   11.0   13.0  test
c  13  -99.0  -99.0  test
d  13    5.0   10.0  test
e   6   11.0   14.0  test
f   0    0.0    0.0     0
g   0    0.0    0.0     0
h   0    0.0    0.0     0


In [ ]:
############################99999999999999999999999999999999999

In [56]:
newDF=df_change.drop_duplicates()
print(newDF)

   one    two  three  four
a      -100.0   14.0  test
b   12   11.0   13.0  test
c   13  -99.0  -99.0  test
d   13    5.0   10.0  test
e    6   11.0   14.0  test
f  NaN    NaN    NaN   NaN
